CREATE TABLE IF NOT EXISTS gold.provider_change_event(
 CHANGE_EVENT_ID STRING,NPI STRING,PROVIDER_ID STRING,CHANGE_TYPE STRING,OLD_VALUE STRING,NEW_VALUE STRING,
 SEVERITY STRING,IDENTITY_CONFIDENCE DECIMAL(5,2),SOURCE_SYSTEM STRING,DETECTION_TIMESTAMP TIMESTAMP,WORKFLOW_STATUS STRING) USING DELTA;
CREATE TABLE IF NOT EXISTS gold.provider_change_summary(
 NPI STRING,PROVIDER_NAME STRING,CHANGE_COUNT INT,PRIMARY_CHANGE_TYPE STRING,HIGHEST_SEVERITY STRING,
 IDENTITY_CONFIDENCE DECIMAL(5,2),WORKFLOW_STATUS STRING,LAST_DETECTED_TIMESTAMP TIMESTAMP) USING DELTA;
CREATE TABLE IF NOT EXISTS gold.provider_cross_source_discrepancy(
 DISCREPANCY_ID STRING,NPI STRING,ATTRIBUTE_NAME STRING,PAYER_VALUE STRING,NPPES_VALUE STRING,PECOS_VALUE STRING,
 STATE_BOARD_VALUE STRING,NPPES_WEIGHT DECIMAL(5,2),PECOS_WEIGHT DECIMAL(5,2),PAYER_ROSTER_WEIGHT DECIMAL(5,2),
 RESOLUTION_STATUS STRING,DETECTED_TIMESTAMP TIMESTAMP) USING DELTA;
